/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;

import javax.swing.JOptionPane;

/**
 *
 * @author PLPASIG
 */
public class SendMoney extends javax.swing.JFrame {
    private String username;

    /**
     * Creates new form SendMoney
     */
    public SendMoney(String username) {
        initComponents();
        this.username = username;
        try {
            connectToDatabase();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public SendMoney() {
        initComponents();
        try {
            connectToDatabase();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    Connection connection;
    Statement statement;
    PreparedStatement preparedStatement;

    private static final String DbName = "bankingsystem";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/" + DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "";

    public void connectToDatabase() {
        try {
            Class.forName(DbDriver);
            connection = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            statement = connection.createStatement();
            if (connection != null) {
                System.out.println("Connected to the database");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void updateBalance(double amount) {
        try {
            String updateSender = "UPDATE accountdetails SET Balance = Balance - ? WHERE Name = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(updateSender);

            preparedStatement.setDouble(1, amount);
            preparedStatement.setString(2, username);

            String updateReceiver = "UPDATE accountdetails SET Balance = Balance + ? WHERE Name = ?";
            PreparedStatement preparedStatement1 = connection.prepareStatement(updateReceiver);

            preparedStatement1.setDouble(1, amount);
            preparedStatement1.setString(2, nameText.getText());

            preparedStatement.executeUpdate();
            preparedStatement1.executeUpdate();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void Transaction(String name, String transactionType) {
        try {
            String queryInsert = "INSERT INTO accounttransactionhistory (name, date, time, type, amount) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(queryInsert);

            preparedStatement.setString(1, name);
            preparedStatement.setDate(2, java.sql.Date.valueOf(LocalDate.now()));
            preparedStatement.setTime(3, java.sql.Time.valueOf(LocalTime.now()));
            preparedStatement.setString(4, transactionType);
            preparedStatement.setString(5, "+" + amountText.getText());

            int rowsInserted = preparedStatement.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("A new transaction was inserted successfully!");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public boolean checkBalance() {
        try {
            int amount = Integer.parseInt(amountText.getText());

            String queryGetBalance = "SELECT balance FROM accountdetails WHERE name = ?";

            PreparedStatement preparedStatement = connection.prepareStatement(queryGetBalance);
            preparedStatement.setString(1, username);

            ResultSet result = preparedStatement.executeQuery();

            if (result.next()) {
                String currentBalance = result.getString("balance");
                int currentBal = Integer.parseInt(currentBalance);
                if (currentBal < amount) {
                    return false;
                } else {
                    return true;
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        amountText = new javax.swing.JTextField();
        sendMoneyButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(50, 1, 47));
        jPanel3.setLayout(null);

        amountText.setBackground(new java.awt.Color(255, 255, 255));
        amountText.setFont(new java.awt.Font("Inter Medium", 0, 24)); // NOI18N
        amountText.setForeground(new java.awt.Color(50, 1, 47));
        amountText.setText("00.00");
        amountText.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        amountText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountTextMouseClicked(evt);
            }
        });
        jPanel3.add(amountText);
        amountText.setBounds(380, 200, 220, 50);

        sendMoneyButton.setBackground(new java.awt.Color(255, 255, 255));
        sendMoneyButton.setFont(new java.awt.Font("Inter Medium", 0, 18)); // NOI18N
        sendMoneyButton.setForeground(new java.awt.Color(50, 1, 47));
        sendMoneyButton.setText("Send");
        sendMoneyButton.setBorderPainted(false);
        sendMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMoneyButtonActionPerformed(evt);
            }
        });
        jPanel3.add(sendMoneyButton);
        sendMoneyButton.setBounds(320, 300, 100, 30);

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Inter Medium", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(50, 1, 47));
        exitButton.setText("EXIT");
        exitButton.setBorderPainted(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(exitButton);
        exitButton.setBounds(600, 350, 70, 20);

        jLabel5.setFont(new java.awt.Font("Inter Medium", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter Amount");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(130, 210, 148, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\Music\\IMG\\bank transfer.png")); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 30, 100, 97);

        jLabel4.setFont(new java.awt.Font("Inter Medium", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Account Name");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(130, 150, 157, 32);

        jLabel2.setFont(new java.awt.Font("Inter Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PHP");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(320, 190, 60, 62);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BANK TRANSFER");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(140, 50, 315, 43);

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("Inter Medium", 2, 14)); // NOI18N
        date.setForeground(new java.awt.Color(0, 0, 0));
        date.setText("April 18, 2005");
        jPanel3.add(date);
        date.setBounds(580, 20, 100, 24);

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.setFont(new java.awt.Font("Inter Medium", 2, 14)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 0));
        time.setText("12:00AM");
        jPanel3.add(time);
        time.setBounds(610, 50, 70, 19);

        nameText.setBackground(new java.awt.Color(255, 255, 255));
        nameText.setFont(new java.awt.Font("Inter Medium", 0, 24)); // NOI18N
        nameText.setForeground(new java.awt.Color(50, 1, 47));
        nameText.setText("Enter Name");
        nameText.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        nameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextMouseClicked(evt);
            }
        });
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        jPanel3.add(nameText);
        nameText.setBounds(320, 130, 280, 50);

        jCheckBox1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText(" Please note that a 2% service charge will be applied to the total amount being transferred.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(120, 260, 500, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PLPASIG\\Music\\IMG\\trans bg.png")); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 20, 660, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameTextActionPerformed

    private void amountTextMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_amountTextMouseClicked
        amountText.setText("");
    }// GEN-LAST:event_amountTextMouseClicked

    private void sendMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendMoneyButtonActionPerformed
        if (nameText.getText().equals("") || nameText.getText().equals("Enter Name")) {
            JOptionPane.showMessageDialog(null, "Please enter the name of the recipient");
        } else if (amountText.getText().equals("") || amountText.getText().equals("00.00")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid amount");
        } else if (!checkBalance()) {
            JOptionPane.showMessageDialog(null, "Insufficient balance!");
        } else if (nameText.getText().equals(username)) {
            JOptionPane.showMessageDialog(null, "You cannot send money to yourself!");
        } else {
            updateBalance(Double.parseDouble(amountText.getText()));
            Transaction(username, "Sent Money");
            Transaction(nameText.getText(), "Received Money");
            JOptionPane.showMessageDialog(null, "Money sent successfully!");

        }
    }// GEN-LAST:event_sendMoneyButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitButtonActionPerformed
        HomePage homePage = new HomePage(username);
        homePage.setVisible(true);
        homePage.pack();
        this.dispose();
    }// GEN-LAST:event_exitButtonActionPerformed

    private void nameTextMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_nameTextMouseClicked
        nameText.setText("");
    }// GEN-LAST:event_nameTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountText;
    private javax.swing.JLabel date;
    private javax.swing.JButton exitButton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton sendMoneyButton;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
